if(OVR_LIBRARY)
    SET(OVR_LIBRARY ${OVR_LIBRARY} CACHE FILEPATH "Path to LibOVR.lib")
else(OVR_LIBRARY)
    SET(OVR_LIBRARY NOTFOUND CACHE FILEPATH "Path to LibOVR.lib")
endif(OVR_LIBRARY)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OVR REQUIRED_VARS OVR_LIBRARY)